# Лабораторная номер 5 по анализу данных на Python

- *Задача 1* 
Разделить таблицу данных так, чтобы в обучающую выборку попало 66% наблюдений, а в тестовую выборку 33% наблюдений

- *Задача 2*
Разделить таблицу данных на четыре одинаковых части.

- *Задача 3*
Разделить таблицу данных на две стратифицированные подвыборки.
По переменным кока-кола и минералка.

## Imports

In [4]:
import random
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [5]:
df = pd.read_csv("./data/beverage_r.csv", sep=";", index_col='numb.obs')
df.head()

          COKE  D_COKE  D_PEPSI  D_7UP  PEPSI  SPRITE  TAB  SEVENUP
numb.obs
1            1       0        0      0      1       1    0        1
2            1       0        0      0      1       0    0        0
3            1       0        0      0      1       0    0        0
4            0       1        0      1      0       0    1        0
5            1       0        0      0      1       0    0        0

## Задача 1

In [7]:
# Создаем массив случайных чисел из равномерного распределения той же длины, что и кол-во наблюдений
random = np.random.uniform(low = 0.0, high=1.0, size=len(df))

# Берем только те наблюдения, где значения из random меньше квантиля 0.66 этой выборки
train = df[random <= np.quantile(random, 0.66)]

print(f"В обучающую выборку попало {len(train) / len(df)} % наблюдений от исходной выборки")
train.head(3)

В обучающую выборку попало 0.6470588235294118 % наблюдений от исходной выборки

          COKE  D_COKE  D_PEPSI  D_7UP  PEPSI  SPRITE  TAB  SEVENUP
numb.obs
3            1       0        0      0      1       0    0        0
4            0       1        0      1      0       0    1        0
5            1       0        0      0      1       0    0        0

In [8]:
test = df[random > np.quantile(random, 0.66)]

print(f"В тестовую выборку попало {len(test) / len(df)} % наблюдений от исходной выборки")
train.head(3)

В тестовую выборку попало 0.35294117647058826 % наблюдений от исходной выборки

          COKE  D_COKE  D_PEPSI  D_7UP  PEPSI  SPRITE  TAB  SEVENUP
numb.obs
3            1       0        0      0      1       0    0        0
4            0       1        0      1      0       0    1        0
5            1       0        0      0      1       0    0        0

## Задача 2

In [10]:
df_first_half, df_second_half = train_test_split(df, test_size=0.5, random_state=42)

print(f"В первой половине наблюдений {len(df_first_half)}, во второй {len(df_second_half)}")

В первой половине наблюдений 17, во второй 17

In [11]:
df_part1, df_part2 = train_test_split(df_first_half, test_size=0.5, random_state=42)
df_part3, df_part4 = train_test_split(df_second_half, test_size=0.5, random_state=42)

print(f"В первой части наблюдений {len(df_part1)}, во второй {len(df_part2)}")
print(f"В третьей части наблюдений {len(df_part3)}, в четвертой {len(df_part4)}")

В первой части наблюдений 8, во второй 9
В третьей части наблюдений 8, в четвертой 9

## Задача 3

In [13]:
# Определение колонок-страт
cols_to_strat_by = ['COKE', 'TAB']

# Создание объединенной колонки-страты (кодируем колонки страты в однку колонку)
new_start_col = df[cols_to_strat_by].apply(lambda x: f"{x[cols_to_strat_by[0]]}/{x[cols_to_strat_by[1]]}", axis=1)

counts = new_start_col.value_counts()

counts  # распределение по по категориям COKE и SPRITE в изначальных данных

1/0    19
0/1    10
0/0     4
1/1     1
Name: count, dtype: int64

In [14]:
# Самая популярная соместная категория
most_common_strata = new_start_col.mode()[0]

# Редкие совместные категории (только одна комбинация значений колонок)
rare_strata_value = counts[counts == 1].index[0]

# Заменяем эти редкие совместные категории на самую популярную совместную категорию
new_start_col_combined = new_start_col.replace(rare_strata_value, most_common_strata)

Делим данные на две стратифицированные подвыборки.

In [16]:
df_strat_part_1, df_strat_part_2 = train_test_split(df, test_size=0.5, stratify=new_start_col_combined)

Смотрим на распределение по колонкам COKE и TAB в первой подвыборке.

In [18]:
df_strat_part_1[cols_to_strat_by].value_counts()

COKE  TAB
1     0      10
0     1       5
      0       2
Name: count, dtype: int64

Смотрим на распределение по колонкам COKE и TAB во второй подвыборке.

In [20]:
df_strat_part_2[cols_to_strat_by].value_counts()

COKE  TAB
1     0      9
0     1      5
      0      2
1     1      1
Name: count, dtype: int64